import type { Metadata } from "next"
import "./globals.css"
import { Suspense } from "react"
import localFont from 'next/font/local'
import Providers from "@/components/Providers"
import MainLayout from "@/components/layout/MainLayout"

const myFont = localFont({
  src: './fonts/Montserrat-VariableFont_wght.ttf',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={myFont.className}>
      <body>
        <Providers>
          <MainLayout>
            <Suspense>
              <main>{children}</main>
            </Suspense>
          </MainLayout>
        </Providers>
      </body>
    </html>
  )
}
